name: Update README

on:
  schedule:
    - cron: "0 0 * * *"  # 매일 00:00 UTC 실행
  workflow_dispatch:

jobs:
  update-readme-and-graph:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update README with recent activity
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "Update README with recent activity"
          MAX_LINES: 5
          COMMIT_NAME: GitHub Activity Readme

      - name: Generate Contribution Graph
        uses: peterxcli/gh-contribution-graph-action@v2.0
        with:
          targets: 'choo121600@apache/airflow'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output_dir: 'images'
          exclude_authored_from_reviewed: true

      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: choo121600
          filename: github-metrics.svg
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Seoul

          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_filter: issue, pr, review, comment
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_achievements: yes
          plugin_followup: yes
          plugin_contributors: yes
          plugin_lines: yes
          plugin_traffic: yes
          plugin_isocalendar: yes
          plugin_notable: yes
          plugin_discussions: yes
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot, vue, scala, c, c++, python, ejs
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_languages_limit: 2

      - name: Commit and push updates
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          
          git add README.md || true
          git add images/*.svg || true
          git add github-metrics.svg || true
          
          git commit -m "Update README, graph, and metrics" || echo "No changes to commit"
          
          git pull --rebase origin main || echo "No changes to rebase"
          
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
