name: Update README

on:
  schedule:
    - cron: "0 0 * * *"  # 매일 00:00 UTC 실행
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Contribution Graph
        uses: peterxcli/gh-contribution-graph-action@v2.0
        with:
          targets: 'choo121600@apache/airflow'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output_dir: 'images'
          exclude_authored_from_reviewed: true
          force: true

      - name: Commit and push updates
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          
          git add README.md || true
          git add images/*.svg || true
          
          git commit -m "Update README, graph" || echo "No changes to commit"
          
          git pull --rebase origin main || echo "No changes to rebase"
          
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
